language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
