language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - CODECLIMATE_REPO_TOKEN=9051ffd89c60b09a41e5f64ab65076b0a58e7a58fbefffd88215fc83df325dd0 bundle exec rake
