version: '2'
services:
  web:
    build: .
    command: bundle exec foreman start
    volumes:
      - bundle_cache:/bundle
      # Map bundle cache to named volume

      - .:/myapp:delegated

    ports:
      - "3003:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "[CHANGE TO MATCH database.yml]"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

volumes:
  bundle_cache:
  my_dbdata:
  redis:
